### ISSUE TITLE
Proposal: add a play for installing the NSO requirements

### ISSUE THREAD

**Issue by ghost** [NSO-developer/nso-ansible-ops#1]
Hi, first thanks for this collection.

You can add a playbook to have the NSO requirements installed, by re-using the linux_ver it can adapt to Redhat or Debian flavor. Just put in vars/OS_type.yml the package name for JDK for example by specifying the variable **openjdk**.
And here's a proposal for the playbook:

```
---
  - name: Install NSO requirements
    hosts: all
    vars_files:
      - [ "vars/{{ linux_ver }}.yml" ]

    tasks:
    - name: check if pip is installed
      command: which pip
      register: pip_task_installed
      changed_when: no
      failed_when: no

    - name: download pip installer
      get_url:
        url=https://bootstrap.pypa.io/get-pip.py
        dest="./get-pip.py"
      become: yes
      when: pip_task_installed is defined and
            pip_task_installed.rc is defined and
            pip_task_installed.rc != 0

    - name: run installer
      command: "{{ ansible_python_interpreter | default('python') }} ./get-pip.py"
      become: yes
      when: pip_task_installed is defined and
            pip_task_installed.rc is defined and
            pip_task_installed.rc != 0
      register: pip

    - name: Install ant
      package:
        name: "ant"
        state: installed

    - name: Install openjdk
      package:
        name: "{{ openjdk }}"
        state: installed

    - name: Copy pip requirements file to remote
      copy:
        src: "{{ playbook_dir }}/files/requirements.txt"
        dest: /tmp/requirements.txt
      register: copy_requirements

    - name: Install pip packages
      when: pip|succeeded and copy_requirements|succeeded
      pip:
        requirements: /tmp/requirements.txt
```

Regards,

Youssef
